spring:
  application:
    name: servicedesk-pro

  datasource:
    url: jdbc:postgresql://localhost:5432/servicedesk
    username: postgres
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org:
#      springframework:
#        security: debug
